CREATE TABLE `platform_admins` (
	`user_id` text PRIMARY KEY NOT NULL,
	`granted_by` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `shopify_roster` (
	`id` text PRIMARY KEY NOT NULL,
	`workspace_id` text NOT NULL,
	`email` text NOT NULL,
	`role` text NOT NULL,
	`shopify_customer_id` text NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspaces`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `roster_unique` ON `shopify_roster` (`workspace_id`,`email`);--> statement-breakpoint
CREATE INDEX `roster_email` ON `shopify_roster` (`email`);--> statement-breakpoint
CREATE INDEX `roster_customer` ON `shopify_roster` (`workspace_id`,`shopify_customer_id`);--> statement-breakpoint
CREATE TABLE `webhook_deliveries` (
	`id` text PRIMARY KEY NOT NULL,
	`workspace_id` text NOT NULL,
	`topic` text NOT NULL,
	`received_at` integer NOT NULL,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspaces`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `webhook_received` ON `webhook_deliveries` (`received_at`);--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_pending_invites` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text NOT NULL,
	`workspace_id` text,
	`role` text,
	`platform_admin` integer DEFAULT false NOT NULL,
	`invited_by` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`workspace_id`) REFERENCES `workspaces`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "invite_kind" CHECK((platform_admin = 0 and workspace_id is not null and role is not null) or (platform_admin = 1 and workspace_id is null and role is null))
);
--> statement-breakpoint
INSERT INTO `__new_pending_invites`("id", "email", "workspace_id", "role", "invited_by", "created_at") SELECT "id", "email", "workspace_id", "role", "invited_by", "created_at" FROM `pending_invites`;--> statement-breakpoint
DROP TABLE `pending_invites`;--> statement-breakpoint
ALTER TABLE `__new_pending_invites` RENAME TO `pending_invites`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `invite_unique` ON `pending_invites` (`email`,`workspace_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `platform_invite_unique` ON `pending_invites` (`email`) WHERE platform_admin = 1;--> statement-breakpoint
ALTER TABLE `events` ADD `source` text DEFAULT 'app' NOT NULL;--> statement-breakpoint
ALTER TABLE `statuses` ADD `shopify_link` text;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `auth_mode` text DEFAULT 'legacy_token' NOT NULL;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `client_id` text;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `encrypted_client_secret` text;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `encrypted_access_token` text;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `access_token_expires_at` integer;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `scopes` text;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `webhooks_registered_at` integer;--> statement-breakpoint
ALTER TABLE `store_connections` ADD `shop_name` text;--> statement-breakpoint
ALTER TABLE `workspace_members` ADD `source` text DEFAULT 'manual' NOT NULL;--> statement-breakpoint
ALTER TABLE `workspaces` ADD `custom_domain` text;--> statement-breakpoint
ALTER TABLE `workspaces` ADD `custom_domain_status` text;--> statement-breakpoint
ALTER TABLE `workspaces` ADD `sending_address` text;--> statement-breakpoint
ALTER TABLE `workspaces` ADD `sending_verified_at` integer;--> statement-breakpoint
ALTER TABLE `workspaces` ADD `roster_tags` text;--> statement-breakpoint
ALTER TABLE `workspaces` ADD `branding` text;--> statement-breakpoint
CREATE UNIQUE INDEX `workspace_custom_domain_unique` ON `workspaces` (`custom_domain`);--> statement-breakpoint
-- Data conversion (hand-written, not generated by drizzle-kit). Roles move
-- from owner / admin / member to manager / staff.
UPDATE `workspace_members` SET `role` = 'manager' WHERE `role` IN ('owner', 'admin');--> statement-breakpoint
UPDATE `workspace_members` SET `role` = 'staff' WHERE `role` = 'member';--> statement-breakpoint
UPDATE `pending_invites` SET `role` = 'manager' WHERE `role` = 'admin';--> statement-breakpoint
UPDATE `pending_invites` SET `role` = 'staff' WHERE `role` = 'member';--> statement-breakpoint
-- The default Shipped and Delivered statuses mirror Shopify's fulfilled and
-- delivered states.
UPDATE `statuses` SET `shopify_link` = 'fulfilled' WHERE `key` = 'shipped';--> statement-breakpoint
UPDATE `statuses` SET `shopify_link` = 'delivered' WHERE `key` = 'delivered';--> statement-breakpoint
-- Events written before the source column: new orders came from Shopify,
-- sync errors from the system, everything else from a person in the app.
UPDATE `events` SET `source` = 'shopify' WHERE `type` = 'order_new';--> statement-breakpoint
UPDATE `events` SET `source` = 'system' WHERE `type` = 'sync_error';
